[feature/pipe] Implementing pipe validator
oh-math/api-nestjs-bp pull request #1
Opened 2023-02-16 19:52 UTC by oh-math

Using pipe for validate the given name ocurrency in the database before its creation.

2023-02-16 22:04 UTC, Joabesv requested changes
Drop **joi** and favor **Zod**, since it's more suited for Typescript applications

2023-02-16 22:06 UTC, Joabesv commented on src/user/user.service.ts
> +    return await this.prisma.user.count(options);
Don't use `Number` as a type. Use number instead
you're calling the constructor, not the type here

2023-02-16 22:13 UTC, Joabesv reviewed
Don't use `Number` as a type. Use number instead

2023-02-16 22:13 UTC, Joabesv commented on src/user/pipe/index.ts
> +export * from './count-name.pipe';
Why use this pattern?

2023-02-16 22:13 UTC, Joabesv commented on src/user/pipe/count-name.pipe.ts
> +import {
Drop **joi** and favor **Zod**

2023-02-17 02:16 UTC, oh-math commented on src/user/pipe/index.ts
> +export * from './count-name.pipe';
You're talking about `barrels`?
This pattern allow you to export all items from a module with a single import, like that:
instead 
`
import { Foo } from './demo/foo.js'
 import { Bar } from './demo/bar.js'
` 
you can just do:
`import {Foo, Bar} from './demo'`

2023-02-17 02:18 UTC, oh-math commented on src/user/user.service.ts
> +    return await this.prisma.user.count(options);
Great reminder, thx!

2023-02-17 02:19 UTC, oh-math commented on src/user/pipe/count-name.pipe.ts
> +import {
gonna open a issue fot that

2023-02-17 14:03 UTC, Joabesv commented on src/user/pipe/index.ts
> +export * from './count-name.pipe';
hmm, I used to think this was very ugly, LOL
but can see the use Cases of it

2023-02-17 14:04 UTC, Joabesv commented on src/user/pipe/count-name.pipe.ts
> +import {
mind if I take it?

2023-02-18 02:03 UTC, oh-math commented on src/user/pipe/count-name.pipe.ts
> +import {
nope, i wanna see that

2023-02-21 19:38 UTC, Joabesv approved these changes

2023-02-21 19:39 UTC, Joabesv commented
LGTM

2023-02-21 19:39 UTC, merged