Feature/auth
oh-math/api-nestjs-bp pull request #3
Opened 2023-03-06 03:50 UTC by oh-math

Implementing not significant local and JWT authentication for learning purpose.

2023-03-06 17:29 UTC, Joabesv commented on prisma/schema.prisma
>  // Address is an embedded document
Nesse contexto o que seria `embedded document`?

2023-03-06 18:17 UTC, Joabesv requested changes

2023-03-06 18:17 UTC, Joabesv commented on src/auth/auth.service.ts
> +    let user: User | null;
user can be a `const`, can't really see why you have done the let way

2023-03-06 18:17 UTC, Joabesv commented on src/auth/auth.service.ts
> +  ): Promise<User | null> {
Return can be inplicit

2023-03-06 18:17 UTC, Joabesv commented on src/auth/strategies/local.strategy.ts
> +  public async validate(email: string, password: string): Promise<User> {
favor return inference

2023-03-07 22:16 UTC, oh-math commented on prisma/schema.prisma
>  // Address is an embedded document
it is just a optional object type with address info, in this way i can segregate some infos. Just something that i CTRL + C and CTRL + V from prisma docs

2023-03-07 22:17 UTC, oh-math commented on src/auth/auth.controller.ts
> +  public async login(@Req() req: any) {
Thx for reminding

2023-03-07 22:36 UTC, oh-math commented on src/auth/auth.controller.ts
> +    return await this.authService.login(req.user);
The return is necessary to retrieve the assigned token, and i need to wait the return coming from the method. CAn you explain better what dou mean in my pvt?

2023-03-07 22:39 UTC, oh-math commented on src/auth/strategies/jwt.strategy.ts
> +  public async validate(payload: PayloadJWT): Promise<PayloadJWT> {
As we have talked about, i gonna maintain like that, and gonna resolve after we talk and you convince me :3

2023-03-07 22:44 UTC, oh-math commented on src/auth/types/payload.type.ts
> +    sub: string;
Can be named whatever you like, it's just a convention for naming IDs in JWT

ref: https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims#registered-claims

go to **Claims registered**

2023-03-07 22:47 UTC, oh-math commented on src/auth/auth.service.ts
> +    let user: User | null;
You are right. Just have followed some code examples and  didn't pay attention

2023-03-07 23:00 UTC, oh-math commented on src/auth/strategies/local.strategy.ts
> +  public async validate(email: string, password: string): Promise<User> {
> As we have talked about, i gonna maintain like that, and gonna resolve after we talk and you convince me :3

Same subject

2023-03-07 23:44 UTC, Joabesv commented on src/auth/types/payload.type.ts
> +    sub: string;
See it now, thx for the ref part, it's really helpful

2023-03-08 01:10 UTC, oh-math commented
> Other details here
> 
> * Before submiting a PR, make sure to run the `lint` command, there are lots of lint mistakes
> * Implement docker to make it easier to test the scenarios (in case you don't want docker cause it's a boilerplate, take a look at this [file database](https://www.prisma.io/docs/concepts/database-connectors/sqlite) approach)
> * I talked about some explicit return types, but it's not only because of syntax, see this [video](https://www.youtube.com/watch?v=I6V2FkW1ozQ) for more info

About lint: i might open an issue to fix. The way is now implemented is default coming from nest

2023-03-08 01:15 UTC, oh-math commented on src/auth/auth.controller.ts
> +  public async login(@Req() req: any) {
Continuing...

Have searched how to type the `@Req` and the express type don't fit and even unknow for some reason

2023-03-08 01:43 UTC, Joabesv commented on src/auth/auth.controller.ts
> +  public async login(@Req() req: any) {
![image](https://user-images.githubusercontent.com/73668618/223597591-90d4116a-a59d-4d5c-815e-81ad7d632454.png)
this way worked here

2023-03-08 01:56 UTC, Joabesv requested changes

2023-03-08 01:56 UTC, Joabesv commented on README.md
> +    npx prisma generate
to keep the pnpm pattern

change from `npx` to `pnpm` it works too

2023-03-08 01:56 UTC, Joabesv commented on src/auth/auth.controller.ts
> +    return this.authService.login(req.user as User);
avoid `as` casting, already said some strategy about this topic

- Avoid `as` casting because you're basic telling the compiler you know it better than him

2023-03-08 01:56 UTC, Joabesv commented on src/auth/auth.service.ts
> +  ): Promise<User | null> {
the one in `validateUser` but it's a discussion for another time

2023-03-09 17:16 UTC, oh-math commented on README.md
> +    npx prisma generate
Wow, you can do that?

2023-03-09 17:56 UTC, Joabesv commented on src/auth/auth.controller.ts
> +  public async login(@Req() req: any) {
hmmm, gonna approve this PR then make some changes in another

so this can finally be merged LOL

2023-03-09 18:14 UTC, Joabesv commented on src/user/user.service.ts
> +import { hashSync } from 'bcrypt';
just a point, since node16.17, core modules should be imported with the `node:prefix`
 read more [here](https://stateful.com/blog/node-18-prefix-only-modules)

2023-03-09 18:15 UTC, Joabesv approved these changes

2023-03-09 18:16 UTC, merged